apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-playlist-db
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.20.200
    path: /nfs/playlist_stg

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-playlist-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-storage

