apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
        version: stable
    spec:
      containers:
        - name: webserver
          image: 192.168.40.200:57777/web-server/react:1.1.15
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: web-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-canary-rules
spec:
  hosts:
    - "*"
  gateways:
    - web-gateway
  http:
    - route:
        - destination:
            host: web-service
            subset: stable
          weight: 90
        - destination:
            host: web-service
            subset: canary
          weight: 10

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: web-canary-grouping
spec:
  host: web-service
  subsets:
    - labels:
        version: stable
      name: stable
    - labels:
        version: canary
      name: canary
