apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    web: react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30300
  externalTrafficPolicy: Local
  type: NodePort
